name: main
run-main: Running main.java file
on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: unbuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Path
        - run: cd src
        - run: cd main
        - run: cd java
      - name: Run main
        run: java main.java